% the setup of the output from model histograms that made the iamges used
% for the NEBEC 2015 conference. this should actually be folded into its
% own function to operate on the data generated by the _modelHistogram_
% function in the future.

inter_hist_data_m = intersubject_hist_data_m;
intra_hist_data_m = intrasubject_hist_data_m;
close all;
opengl software;
% histogram of intrasubject and intersubject, mahal
psuedo_inter_mahal = inter_hist_data_m;
psuedo_inter_mahal(psuedo_inter_mahal>5000) = 5000;
hist_distance = max(max([intra_hist_data_m;psuedo_inter_mahal]));
x = 0:1:hist_distance;
y1 = intra_hist_data_m;
[n1,x] = hist(y1,x);
y2 = psuedo_inter_mahal;
[n2,x] = hist(y2,x);

n1 = n1./sum(n1);
n2 = n2./sum(n2);

h1 = figure('name','Mahalanobis Distance Histogram','numbertitle','off');
set(h1,'position',[0 0 800 800]);
box on;
bar(x,[n1;n2]','grouped');grid on;
axis([ 0 hist_distance*1.1 0 max(max([n1;n2]))*1.1]);
title('Histogram of Separable Mahalanobis Distances');
xlabel(' Distance between groups');
ylabel(' Percentage of samples ');
legend('Internal Cluster Distance','External Cluster Distance','Location','SouthOutside','orientation','horizontal')

h2=axes('position',[0.25 0.62 0.5 0.25]);
box on;
axis on;
hist_distance = max( intra_hist_data_m );
x2 = 0:1:hist_distance;
[y2,x] = hist(intra_hist_data_m,x2);
y2 = y2./sum(y2);
bar(x,y2);grid on;
set(gca,'LineWidth',1.2');
xlim([10 90]);
title('Internal Cluster Distance');
xlabel(' Distance between groups');
ylabel(' Percentage of samples ');

h3=axes('position',[0.25 0.24 0.5 0.25]);
box on;
axis on;
% intersubject_hist_data_m( intersubject_hist_data_m > mean(intersubject_hist_data_m) ) = mean(intersubject_hist_data_m);
hist_distance_max = 0.00001*mean( inter_hist_data_m )*2;
hist_distance_min = 0.00001*mean( inter_hist_data_m )*0.25;
x3 = hist_distance_min:10:hist_distance_max;
[y3,x] = hist(inter_hist_data_m,x3);
y3 = y3./sum(y3);
bar(x,y3,'r');grid on;
set(gca,'LineWidth',1.2');
xlim([hist_distance_min*0.9 hist_distance_max*1.1]);
title('External Cluster Distance');
xlabel(' Distance between groups');
ylabel(' Percentage of samples ');

% on the same figure?
hist_distance = max(max([intrasubject_hist_data;intersubject_hist_data]));
x = 0:1:hist_distance;
y1 = intrasubject_hist_data;
[n1,x] = hist(y1,x);
y2 = intersubject_hist_data;
[n2,x] = hist(y2,x);

n1 = n1./sum(n1);
n2 = n2./sum(n2);

figure('name','Euclidean Distance Histogram','numbertitle','off');
bar(x,[n1;n2]','grouped');grid on;
box on;
set(gca,'LineWidth',1.1');
axis([ 0 hist_distance*1.1 0 max(max([n1;n2]))*1.1]);
title('Histogram of Separable Euclidean Distances');
xlabel(' Distance between groups');
ylabel(' Percentage of samples ');
legend('Within Cluster Epoch Distance','External Cluster Distance','Location','SouthOutside','orientation','horizontal')

axes('position',[0.3 0.27 0.5 0.25]);
box on;
bar(x,n1,'b');grid on;
set(gca,'LineWidth',1.2');
xlim([0 100]);
title('Internal Cluster Distance');
xlabel(' Distance between groups');
ylabel(' Percentage of samples ')

axes('position',[0.3 0.63 0.5 0.25]);
box on;
bar(x,n2,'r');grid on;
set(gca,'LineWidth',1.2');
xlim([0 100]);
title('External Cluster Distance');
xlabel(' Distance between groups');
ylabel(' Percentage of samples ')